// PRD: §F-DOC-1/3/4 — deterministic static build with the [BB-241] link gate.
//
// Pipeline: load pages (fs + front matter + render pass 1) → validate the
// manifest → resolve/rewrite every site link (render pass 2 with the resolver
// injected) → any violation throws one coded [BB-241] error listing ALL of
// them, before anything touches the disk → write the themed pages, the
// generated index and the collected assets. Output is byte-reproducible:
// manifest order, sorted asset writes, no timestamps/random ids/absolute paths
// (all hrefs are route-relative).
import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { renderMarkdown } from './markdown.js';
import { makeLinkResolver } from './links.js';
import { loadSite, pageDescription, pageTitle, siteNav } from './site.js';
import { renderIndex, renderPage } from './theme.js';
import type { BuildReport, DocsSite, LinkIssue, LoadedPage } from './types.js';

/**
 * Marker written into the output directory. prepareOutDir refuses to clean a
 * non-empty directory without it, so `--out` can never wipe a foreign folder.
 */
export const SITE_MARKER = '.breadesp-docs-site';

const MARKER_CONTENT =
  'This directory is generated by `pnpm docs:build` (packages/docs-site). Safe to delete and rebuild.\n';

/** Everything the build computes before the first write (throw point = gate). */
interface PreparedSite {
  pages: LoadedPage[];
  nav: ReturnType<typeof siteNav>;
  /** Repo-relative asset source → site asset route. */
  assets: Map<string, string>;
  linkCount: number;
}

/**
 * Load, render and link-check the whole site without writing anything.
 * Throws the coded [BB-241] error when any content violation exists.
 */
function prepareSite(site: DocsSite): PreparedSite {
  const { pages, issues: loadIssues } = loadSite(site);
  const issues: LinkIssue[] = [];

  // Manifest hygiene: routes and sources must be unique (else output is
  // ambiguous) and the tutorials section must be non-empty (PRD §F-DOC-2).
  const routeOwners = new Map<string, string[]>();
  const sourceOwners = new Map<string, number>();
  for (const page of site.pages) {
    routeOwners.set(page.route, [...(routeOwners.get(page.route) ?? []), page.sourcePath]);
    sourceOwners.set(page.sourcePath, (sourceOwners.get(page.sourcePath) ?? 0) + 1);
  }
  for (const [route, owners] of routeOwners) {
    if (owners.length > 1) issues.push({ page: route, target: route, line: 0, reason: `duplicate route claimed by ${owners.join(', ')}` });
  }
  for (const [sourcePath, count] of sourceOwners) {
    if (count > 1) issues.push({ page: sourcePath, target: sourcePath, line: 0, reason: 'source listed more than once in the manifest' });
  }
  if (!pages.some((p) => p.source.section === 'tutorials')) {
    issues.push({ page: '(manifest)', target: 'docs/tutorials', line: 0, reason: 'no tutorial pages discovered under docs/tutorials (PRD §F-DOC-2)' });
  }

  const anchorsByRoute = new Map<string, Set<string>>(
    pages.map((p) => [p.source.route, new Set(p.rendered.headings.map((h) => h.slug))]),
  );
  const routeBySource = new Map<string, string>(pages.map((p) => [p.source.sourcePath, p.source.route]));
  const assets = new Map<string, string>();
  let linkCount = 0;

  // Pass 2: re-render with the link resolver injected; the resolver records
  // violations and rewrites hrefs to route-relative output paths.
  const resolvedPages: LoadedPage[] = pages.map((page) => {
    const resolveLink = makeLinkResolver({ site, current: page.source, anchorsByRoute, routeBySource, issues, assets });
    const rendered = renderMarkdown(page.body, { resolveLink });
    linkCount += rendered.links.length;
    return { ...page, rendered };
  });

  if (loadIssues.length > 0 || issues.length > 0) {
    const lines = [
      ...loadIssues.map((issue) => `  - ${issue}`),
      ...issues.map((issue) => `  - ${issue.page}${issue.line > 0 ? `:${issue.line}` : ''}: ${issue.reason} (target: ${issue.target})`),
    ];
    throw new Error(`[BB-241] docs site content validation failed (${lines.length} issue${lines.length === 1 ? '' : 's'}):\n${lines.join('\n')}`);
  }
  return { pages: resolvedPages, nav: siteNav(resolvedPages), assets, linkCount };
}

/** Validate-only entry (`pnpm docs:check`): the full gate, zero writes. */
export function checkSite(site: DocsSite): { pageCount: number; linkCount: number } {
  const prepared = prepareSite(site);
  return { pageCount: prepared.pages.length, linkCount: prepared.linkCount };
}

/**
 * Reset the output directory. Safety gate ([BB-242]): a non-empty directory
 * that was not produced by this builder (no marker file) is never cleaned.
 */
function prepareOutDir(outDir: string): void {
  if (existsSync(outDir)) {
    if (!statSync(outDir).isDirectory()) {
      throw new Error(`[BB-242] output path '${outDir}' exists and is not a directory`);
    }
    const entries = readdirSync(outDir);
    if (entries.length > 0 && !entries.includes(SITE_MARKER)) {
      throw new Error(
        `[BB-242] output directory '${outDir}' is not empty and was not generated by docs:build (missing ${SITE_MARKER}); refusing to clean it — pick a fresh directory`,
      );
    }
    for (const entry of entries) rmSync(join(outDir, entry), { recursive: true, force: true });
  }
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, SITE_MARKER), MARKER_CONTENT, 'utf8');
}

/**
 * Build the site into outDir. All content gates run before the first write;
 * a failed build never leaves a half-written site behind in a foreign dir.
 */
export function buildSite(site: DocsSite, outDir: string): BuildReport {
  const prepared = prepareSite(site);
  prepareOutDir(outDir);

  const writes: { route: string; html?: string; copyFrom?: string }[] = [];
  for (const page of prepared.pages) {
    writes.push({
      route: page.source.route,
      html: renderPage({
        title: pageTitle(page),
        route: page.source.route,
        contentHtml: page.rendered.html,
        headings: page.rendered.headings,
        nav: prepared.nav,
        pageCount: prepared.pages.length,
      }),
    });
  }
  writes.push({
    route: 'index.html',
    html: renderIndex({
      route: 'index.html',
      nav: prepared.nav,
      pageCount: prepared.pages.length,
      cards: prepared.nav.sections.map((section) => ({
        sectionTitle: section.title,
        pages: section.pages.map((navPage) => {
          const loaded = prepared.pages.find((p) => p.source.route === navPage.route);
          return { route: navPage.route, title: navPage.title, description: loaded ? pageDescription(loaded) : '' };
        }),
      })),
    }),
  });
  const assetRoutes = [...prepared.assets.entries()].sort((a, b) => (a[1] < b[1] ? -1 : a[1] > b[1] ? 1 : 0));
  for (const [sourcePath, assetRoute] of assetRoutes) {
    writes.push({ route: assetRoute, copyFrom: join(site.rootDir, sourcePath) });
  }

  const files: string[] = [SITE_MARKER];
  try {
    for (const write of writes) {
      const target = join(outDir, write.route);
      mkdirSync(dirname(target), { recursive: true });
      if (write.html !== undefined) writeFileSync(target, write.html, 'utf8');
      else if (write.copyFrom !== undefined) copyFileSync(write.copyFrom, target);
      files.push(write.route);
    }
  } catch (err) {
    throw new Error(`[BB-242] failed to write the docs site into '${outDir}': ${err instanceof Error ? err.message : String(err)}`);
  }
  files.sort();
  return { outDir, pageCount: prepared.pages.length, files, linkCount: prepared.linkCount };
}
